config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: "posts#index"

  get 'posts/posts_for_admin', to: 'posts#posts_for_admin'
  get 'posts/user_posts',   to: 'posts#user_posts'
  get 'posts/search_result', to: 'posts#search_result'
  resources :posts do
    resources :images, only: [:create , :destroy]
  end
  resources :categories , only: [:create , :new , :destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)


    
    # Define abilities for the passed in user here. For example:
    #
   #user ||= User.new # guest user (not logged in)
   
   if user.admin?
     can :create, Category
     can :manage, User
     can :edit , Post do |post|
     post.status == Post.statuses[:new_post] || post.user_id == user.id
     end
   else
     can :create, Post 

     can :delete, Post do |post|
      post.user_id == user.id
     end
     
     can :edit, Post do |post|
      post.user_id = user.id &&(post.status == Post.statuses[:draft] || post.status == Post.statuses[:archived])
     end

     can :manage, User do |u|
      u.id == user.id
     end

     can :read , Post
   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts
  validates :title , presence: true
end
=begin

  include PgSearch
  multisearchable against: :title

  after_save :reindex

  private

  def reindex
    PgSearch::Multisearch.rebuild(Category)
  end
end
=end

app/models/post.rb
# frozen_string_literal: true

$LOAD_PATH << File.join(__dir__, 'lib')
require 'posts_method.rb'

class Post < ApplicationRecord
  POST_LIFETIME = 3.days

  include PgSearch::Model
  pg_search_scope :search_everywhere, against: %i[header body]

  validates :header, :body, presence: true
  belongs_to :user
  belongs_to :category

  mount_uploaders :images, AttachmentUploader

  accepts_nested_attributes_for :category, reject_if: :all_blank, allow_destroy: true

  # after_save :reindex

  enum status: {
    draft: 'draft',
    new_post: 'new_post',
    rejected: 'rejected',
    approved: 'approved',
    published: 'published',
    archived: 'archived'
  }

  def self.publish_posts
    posts = Post.where('status = ?', Post.statuses[:approved])
    posts.each(&:published!)
  end

  def self.archive_posts
    posts = Post.where('status = ?', Post.statuses[:published])
    posts.each do |post|
      post.archived! if Time.now - post.created_at >= POST_LIFETIME
    end
  end
end
#   private
#
#
#   def reindex
#     PgSearch::Multisearch.rebuild(Post)
#   end
# end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, dependent: :destroy
end
=begin
  

  include PgSearch
  multisearchable against: :user_name

  after_save :reindex

  private

  def reindex
    PgSearch::Multisearch.rebuild(User)
  end

end
=end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[user_name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[user_name email password current_password])
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def new; end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to posts_path
    else
      render new_category_path
    end
  end

  def destroy 
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def category_params
    params.permit(:title)
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

$LOAD_PATH << File.join(__dir__, "lib")
require 'images_method.rb'

class ImagesController < ApplicationController
  include ImagesMethods
  before_action :set_posts_image

  def create
    if params[:post].blank?
      redirect_back(fallback_location: root_path)
    else
      add_more_images(images_params[:images])
      flash[:error] = 'Failed uploading images' unless @post.save
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    flash[:error] = 'Failed deleting image' unless @post.save
    redirect_back(fallback_location: root_path)
  end

  private

  def set_posts_image
    @post = Post.find(params[:post_id])
  end

  def images_params
    if params[:post].blank?
      redirect_back(fallback_location: root_path)
    else
      params.require(:post).permit({ images: [] })
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

$LOAD_PATH << File.join(__dir__, "lib")
require 'posts_method.rb'

class PostsController < ApplicationController
  include PostsMethods

  before_action :authenticate_user!, except: %i[index show search_result]
  before_action :set_post, only: %i[show edit update destroy]  

  def index
    #@posts = Post.includes(:user).where('status = ?', 'published').page(params[:page])
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).where('status = ?', 'published').includes(:user).includes(:category).page(params[:page])
    
    respond_to do |format|
      format.html  #index.html.erb
      format.json { render json: @posts }
      format.js #index.js.erb
    end
    #byebug
  end

  def show; end

  def new
    @categories = Category.all
    #byebug
    @post = Post.new
    authorize! :create, @post
    @post.build_category

    # byebug
  end

  def create
    @post = Post.new(post_params)
    # byebug
    @post.user_id = current_user.id

    @post.status = params[:status]

    if @post.save
      redirect_to '/posts/' + @post.id.to_s
    else
      render '/posts/new'
    end
  end

  def edit
    #@post = Post.find(params[:id])
    
    authorize! :edit, @post
    @categories = Category.all
    @empty_category = find_empty_category
    
  end

  def update
    @post.status = params[:status]

    if @post.update(post_params)
      redirect_to '/posts/' + @post.id.to_s
    else
      render '/posts/' + @post.id.to_s + '/edit'
    end
  end

  def destroy
    
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:header, :body, :category_id, { images: [] }, category_attributes: [:title,:_destroy])
  end

  def set_post
    @post = Post.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def find_published_categories
        posts = Post.where('status = ?', 'published')
        published_category = []
        posts.each do |post| 
            published_category << post.category
        end
        published_category.uniq
    end

    def find_published_users
        posts = Post.where('status = ?', 'published')
        published_users = []
        posts.each do |post| 
            published_users << post.user
        end
        published_users.uniq
    end
end

app/views/categories/new.html.slim
= form_with model: @category , url: categories_path  , method: "post"  do |c|
  .container
    h1 New category
    .input-group.mb-3
      .input-group-prepend
        = c.label :title, class: "input-group-text"
      = c.text_field :title, class: "form-control"
    .mt-3
      = c.submit 'Create', class:"btn btn-success mb-2"

app/views/layouts/_nav_bar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand href="#"  Navbar w/ text
  button.navbar-toggler aria-controls="navbarText" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarText" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  #navbarText.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        a.nav-link href="/posts"  Home
      - if user_signed_in? && !current_user.admin?
        li.nav-item 
          a.nav-link href="/posts/user_posts" Users posts
      - if user_signed_in? && current_user.admin?
        li.nav-item
          a.nav-link href="/posts/posts_for_admin"  Posts for approval
    = form_tag posts_search_result_path, method: :get, role: 'search' do
      = text_field_tag :query, params[:query]
      = submit_tag "Search", class: 'ml-2 btn btn-info'
    - if user_signed_in?
      .btn-group
        button.btn.btn-outline-dark.dropdown-toggle.ml-2 aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button" 
          = current_user.user_name
        .dropdown-menu.dropdown-menu-right
          = link_to 'Create post', new_post_path, class: "dropdown-item" unless current_user.admin?
          = link_to 'Edit profile', edit_user_registration_path,  class: "dropdown-item"
          = link_to 'Sign Out', destroy_user_session_path, method: :delete , class: "dropdown-item"
    - else
      a.btn.btn-outline-dark.mx-2.my-sm-0 href= new_user_session_path role="button" Sign in
      a.btn.btn-outline-dark.mx-2.my-sm-0 href= new_user_registration_path role="button" Sign up

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title ADS
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render partial: "layouts/nav_bar"
    = yield

app/views/posts/_form.html.slim
.container
  - if @post.errors.any?
    - @post.errors.each do |attr,message|
      .alert.alert-danger role="alert" 
        = attr
        = message
  = form_for @post , url: path , multiple: true ,method: method  do |post|
    .container
      - if method.to_s == "post"
        h1 New Post
      - else
        h1 Edit Post
      .input-group.mb-3
        .input-group-prepend
          = post.label :header, class: "input-group-text"
        = post.text_field :header, class: "form-control" ,readonly: (true if current_user.admin?)
      .input-group.mb-3
        .input-group-prepend
          = post.label :body, class: "input-group-text"
        = post.text_area :body , class: "form-control", readonly: (true if current_user.admin?)
      = post.file_field(:images , multiple: true) unless current_user.admin? || !@post.new_record?
      hr/
      - @post.images.each_with_index do |image,index|
        - if @post.images?
          = image_tag(image.thumb.url, alt: 'Image' , class:"mb-2" )
          = link_to("Delete", post_image_path(@post, index), :method => :delete, data: { confirm: "Are you sure you want to delete this image?" }) unless current_user.admin?
      hr/
      - if can? :create , Category
        .form-group
          label for="exampleFormControlSelect1"  Choose category
          = select(:post,:category_id, options_from_collection_for_select(@categories, "id", "title",  @post.category_id ),{},{class: "form-control"})
        .form-group
          h3 Or create a category:
          = post.fields_for :category, Category.new do |category|
            = category.label  "New category title:"
            = category.text_field :title,  class: "form-control"
        h3 You can delete category without posts
        - @empty_category.each do |category|
          label= category.title
          = link_to("Delete", category_path(category), :method => :delete, data: { confirm: "Are you sure you want to delete this category?" },id: 'delete_category')
          br/
      .mt-3
        - if current_user.admin?
          = post.button "Approved"  , class: "btn btn-success mb-2 mr-2" , name: "status", value: "approved"
          = post.button "Reject"  ,class: "btn btn-success mb-2 mr-2" , name: "status", value: "rejected"
        - else
          = post.button "Piblish" , class: "btn btn-success mb-2 mr-2" , name: "status", value: "new_post"
          = post.button "Save as draft" ,class: "btn btn-success mb-2 mr-2" , name: "status", value: "draft"
        = link_to('Delete', post_path ,class: "btn btn-danger mb-2", method: :delete , data: { confirm: 'Are you sure?' }) if path == "/posts/#{@post.id}"
  - unless @post.new_record? || current_user.admin?
    = form_with model: @post , url: post_images_path(@post) ,method: :post  do |post|
      = post.file_field :images, multiple: true
      = post.submit

app/views/posts/_index.html.slim
.container
  .row.mt-6.my-3
    .col-lg-12
      .row
        - @posts.each do |post|
          .card.mx-3.my-3.text-center style=("width: 18rem;") 
            .card-body
              h5.card-title= post.header
              h6.card-subtitle.mb-2.text-muted
              | author:#{post.user.user_name}
              h6.card-subtitle.mb-2.text-muted
              | categoy:#{post.category.title}
              p.card-text= post.body
              a.card-link href="/posts/#{post.id}"  Link
    = paginate @posts , theme: 'twitter-bootstrap-4'

app/views/posts/_index_form.html.slim
.container
  .row.mt-6.my-3
    .col-lg-12
      .row
        - @posts.each do |post|
          .card.mx-3.my-3.text-center style=("width: 18rem;") 
            .card-body
              h5.card-title= post.header
              h6.card-subtitle.mb-2.text-muted
                | author:#{post.user.user_name}
              h6.card-subtitle.mb-2.text-muted
                | status:#{post.status}
              p.card-text= post.body
              .btn-group.btn-group-sm.mx-2.mb-2 role="group" 
                - if post.status==Post.statuses[:draft] || (post.status==Post.statuses[:new_post] && current_user.admin?)
                  a.btn.btn-secondary.bg-light.text-muted.border.border-white href="/posts/#{post.id}/edit"  Edit
                = link_to 'Delete', post,class: "btn btn-secondary bg-light text-muted border border-white", method: :delete, data: { confirm: 'Are you sure?' }
    = paginate @posts , theme: 'twitter-bootstrap-4'

app/views/posts/edit.html.slim
= render partial: "form" , locals: {path: "/posts/#{@post.id}" , method: "PATCH"}

app/views/posts/index.html.slim
#indexDiv.container
  .row.mt-6.my-3
    h3 All Posts
    
    .col-lg-12
    = search_form_for @q , :remote=>"true", url: posts_path, html: {method: :get}  do |f|
      .container
        .input-group.mb-2
          = f.label 'Сategory search', class: 'mr-2'
          = f.select :category_id_eq, options_from_collection_for_select(find_published_categories, "id", "title", @q.category_id_eq), include_blank: true 
        .input-group.mb-2
          = f.label 'User search', class: 'mr-2'
          = f.select :user_id_eq, options_from_collection_for_select(find_published_users, "id", "user_name", @q.user_id_eq), include_blank: true
      = f.submit 'Search',class: "btn btn-light"

      .sort_index
        = render partial: "index"
  

app/views/posts/index.js.slim
| $(".sort_index").html("#{escape_javascript(render 'index')}");

app/views/posts/new.html.slim
= render partial: "form" , locals: {path: "/posts" , method: "post"}

app/views/posts/posts_for_admin.html.slim
= render partial: "index_form" , locals: {path: "/posts" , method: "path"}

app/views/posts/search_result.html.slim
.container
  h3 Search results
  .row.mt-6.my-3
    .col-lg-12
      .row
        - @search_results.each do |result|
          .card.mx-3.my-3.text-center style=("width: 18rem;") 
            .card-body
              h5.card-title= result.header
              h6.card-subtitle.mb-2.text-muted
              | author:#{result.user.user_name}
              h6.card-subtitle.mb-2.text-muted
              | categoy:#{result.category.title}
              p.card-text= result.body
              a.card-link href="/posts/#{result.id}"  Link

app/views/posts/show.html.slim
form
  .container
    h4 Show post
    hr/
    .form-group.row
      label.col-sm-2.col-form-label Header:
      .col-sm-10
        label.col-sm-2.col-form-label= @post.header
    .form-group.row
      label.col-sm-2.col-form-label for="inputPassword"  Body:
      .col-sm-10
        label.col-sm-2.col-form-label= @post.body
    .form-group.row
      label.col-sm-2.col-form-label for="inputPassword"  Author:
      .col-sm-10
        label.col-sm-2.col-form-label= @post.user.user_name
    .form-group.row
      label.col-sm-2.col-form-label for="inputPassword"  Category:
      .col-sm-10
        label.col-sm-2.col-form-label= @post.category.title
    #carouselExampleControls.carousel.slide data-ride="carousel" 
      .carousel-inner
        - @post.images.each do |image|
          div class=("carousel-item #{"active" if @post.images[0] == image}") 
            = image_tag(image.thumb.url, alt: 'Image' , class:"rounded-top" ) if @post.images?
      a.carousel-control-prev data-slide="prev" href="#carouselExampleControls" role="button" 
        span.carousel-control-prev-icon aria-hidden="true" 
        span.sr-only Previous
      a.carousel-control-next data-slide="next" href="#carouselExampleControls" role="button" 
        span.carousel-control-next-icon aria-hidden="true" 
        span.sr-only Next

app/views/posts/user_posts.html.slim
.container
  .row.mt-6.my-3
    h3
      | User Posts 
    .col-lg-12
      .row
        - @posts.each do |post|
          .card.mx-3.my-3.text-center[style="width: 18rem;"]
            .card-body
              h5.card-title
                = post.header
              h6.card-subtitle.mb-2.text-muted
                | id:
                = post.id
              h6.card-subtitle.mb-2.text-muted
                | author:
                = post.user.user_name
              h6.card-subtitle.mb-2.text-muted
                | status:
                = post.status
              p.card-text
                = post.body
              .btn-group.btn-group-sm.mx-2.mb-2[role="group"]
                - if post.status==Post.statuses[:draft] || post.status==Post.statuses[:archived]
                  |  <a href="/posts/
                  = post.id
                  | /edit" class="btn btn-secondary bg-light text-muted border border-white">Edit 
                = link_to 'Delete', post,class: "btn btn-secondary bg-light text-muted border border-white", method: :delete, data: { confirm: 'Are you sure?' }
  = paginate @posts , theme: 'twitter-bootstrap-4'